docs_dir: docs
site_name: openfoodfacts-python
site_url: https://openfoodfacts.github.io/openfoodfacts-python
site_dir: gh_pages

nav:
  - Home: 'index.md'
  - Usage: 'Usage.md'

theme:
  name: material
